[build]
  base = "/"
  publish = "build/web"
  command = "bash ./build.sh"

[build.environment]
  FLUTTER_HOME = "/opt/flutter"
  PATH = "/opt/flutter/bin:/opt/flutter/bin/cache/dart-sdk/bin:$PATH"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
